<a href="https://colab.research.google.com/github/KaiyaBullock/MAT421/blob/main/ModD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra
### 1.2.1 Linear Combinations
A linear combination is a vector made by multiplying individual vectors by a scaler and adding the resulting vectors. A linear subspace is a result of linear combinations.

The below exmaple writes the vector [1,4,5] as a linear combination of vectors

In [1]:
import numpy as np

vector_one = np.array([0,2,2])
vector_two = np.array([1,0,1])

x = vector_one*2
y = vector_two*1

z = np.array([1,4,5])

result = x + y
print(result)
print(result == z)

[1 4 5]
[ True  True  True]


### 1.2 Linear Independence and Dimension
A set of vectors are **linearly independent** if none of them can be written as a combination of the other, in otherwords there is no redundancy. With linearly independent vectors, the only way to get to the zero vector would to multiply by a scalar of zero.

A **Basis** is a set of linearly independent vectors that generates every element of the vector space

The dimension of a vector spece is equal to the number of elememts. The **Dimension Theorem** says that for any linear subspace U of V, any basis or bases of U will have the same number of elements, $dim(U)$

In the below example we check if given vectors are linearly independent by setting them equal to the zero vector. This equation is set up as $c_{1}*vec1 + c_{2}*vec2 +c_{3}*vec3 = [0,0,0]$, so if we recieve a result of [0,0,0], the vectors are linearly independent

In [9]:
A = np.array([[4,3,5], [5,2,1], [4,7,8]])
B = np.array([[1,2,3], [5,2,3], [3,7,9]])
z = np.array([0,0,0])

x = np.linalg.solve(A,z)
y - np.linalg.solve(B,z)

print(x)
print(y)

[0. 0. 0.]
[0 0 0]


### Orthonormal Bases
A list of vectors $s$ {$u_1, ..., u_m$} is **orthonormal** if all of the vectors are pairwise orthogonal and each has a norm of one

Let $U⊆V$ be a linear subspece with orthonormal basis $q_1, ..., q_m$. The **Orthonormal Projection** of v∈V on $U$ is $P_U v = ∑_{j=1}^{m}⟨v, q_j⟩ q_j$

**Best Approxiamtion Theorem**: Let $U⊆V$ be a linear subspace with orthogonal basis $q_1,...,q_m$ and let v∈V. For any u∈U, $||v-P_U v|| ≤  ||v-u||$

**Pythagorean Theorem**: Let $u,v∈V$ be orthogonal. Then $||u+v||^2 = ||u||^2 + ||v||^2$

**Cauchy-Schwarz**: For any $u,v∈V, |⟨u,v⟩|≤ ||u||*||v||$

**Gram-Schmidt**: Let $a_1,...,a_m$ in $R^n$ be linearly independent. Then there exist an orthonormal basis $q_1,...,q_m$ of $span(a_1,...,a_m)$

### Eigenvalues and Eigenvectors
Let $A$ be a square matrix in the real number system. Then $λ∈R$ is an **eigenvalue** of $A$ if there exists a nonzero vector $x$ such that $Ax = λx$. This vector x is the **eigenvector**

The code below finds the eigenvalue and eigenvector for a given vector space

In [11]:
import numpy as np
from numpy.linalg import eig

x = np.array([[1,2], [3,5]])
w,v = eig(x)

print('Eigenvalue:', w)
print('Eigenvector:', v)

Eigenvalue: [-0.16227766  6.16227766]
Eigenvector: [[-0.86460354 -0.36126098]
 [ 0.50245469 -0.93246475]]


### 1.3 Linear Regression
**QR Decompression** breaks down a matrix $A$ into two matricies that produce $A$ when multiplied together ($A = QR$). These matricies $Q$ and $R$ can be found using the Gram-Schmidt process.

In [13]:
import numpy as np
from numpy.linalg import qr

x = np.array([[1,3], [4,7]])

Q,R = qr(x)
print('Q:', Q)
print('R:', R)

y = np.dot(Q,R)
print('QR:', y)

iterations = [1,20]
for i in range(20):
  Q,R = qr(x)
  x = np.dot(R,Q)
  if i+1 in iterations:
    print(f'Iteration {i+1}:')
    print(x)

Q: [[-0.24253563 -0.9701425 ]
 [-0.9701425   0.24253563]]
R: [[-4.12310563 -7.51860438]
 [ 0.         -1.21267813]]
QR: [[1. 3.]
 [4. 7.]]
Iteration 1:
[[ 8.29411765  2.17647059]
 [ 1.17647059 -0.29411765]]
Iteration 20:
[[ 8.58257569e+00 -1.00000000e+00]
 [ 7.82988236e-23 -5.82575695e-01]]


### Least Squares Problems
The system $Ax=b$ is often inconsistent. Thus, we look to use $Ax$ to approximate $b$. In this case we are interested in overdetermined systems where $n>m$. With the QR breakdown we get $Rx=Q^Tb$ which can be solved by backwards substitution.